/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddProductRequest {
  'stockQty' : bigint,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'discountPercent' : bigint,
  'imageUrl' : string,
  'category' : string,
  'rating' : number,
  'price' : bigint,
  'reviewCount' : bigint,
}
export interface CreateOrderRequest {
  'customerName' : string,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : string,
  'upiTransactionId' : [] | [string],
  'shippingAddress' : ShippingAddress,
  'customerId' : string,
  'items' : Array<OrderItem>,
  'customerEmail' : string,
}
export interface Order {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : string,
  'createdAt' : Timestamp,
  'upiTransactionId' : [] | [string],
  'totalAmount' : bigint,
  'shippingAddress' : ShippingAddress,
  'customerId' : string,
  'items' : Array<OrderItem>,
  'customerEmail' : string,
}
export type OrderId = string;
export interface OrderItem {
  'qty' : bigint,
  'productId' : ProductId,
  'productName' : string,
  'priceAtOrder' : bigint,
}
export type OrderStatus = { 'Paid' : null } |
  { 'Delivered' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export type PaymentMethod = { 'COD' : null } |
  { 'UPI' : null };
export interface Product {
  'id' : ProductId,
  'stockQty' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'description' : string,
  'discountPercent' : bigint,
  'updatedAt' : Timestamp,
  'imageUrl' : string,
  'category' : string,
  'rating' : number,
  'price' : bigint,
  'reviewCount' : bigint,
}
export type ProductId = string;
export interface ShippingAddress {
  'city' : string,
  'postalCode' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : [] | [string],
}
export type Timestamp = bigint;
export interface UpdateProductRequest {
  'id' : ProductId,
  'stockQty' : bigint,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'discountPercent' : bigint,
  'imageUrl' : string,
  'category' : string,
  'rating' : number,
  'price' : bigint,
  'reviewCount' : bigint,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[AddProductRequest], Product>,
  'createOrder' : ActorMethod<[CreateOrderRequest], Order>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getFeaturedProducts' : ActorMethod<[string], Array<Product>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getOrdersByCustomer' : ActorMethod<[string], Array<Order>>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], [] | [Order]>,
  'updateProduct' : ActorMethod<[UpdateProductRequest], [] | [Product]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];