/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AddProductRequest = IDL.Record({
  'stockQty' : IDL.Nat,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const ProductId = IDL.Text;
export const Timestamp = IDL.Int;
export const Product = IDL.Record({
  'id' : ProductId,
  'stockQty' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'updatedAt' : Timestamp,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const PaymentMethod = IDL.Variant({
  'COD' : IDL.Null,
  'UPI' : IDL.Null,
});
export const ShippingAddress = IDL.Record({
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Opt(IDL.Text),
});
export const OrderItem = IDL.Record({
  'qty' : IDL.Nat,
  'productId' : ProductId,
  'productName' : IDL.Text,
  'priceAtOrder' : IDL.Nat,
});
export const CreateOrderRequest = IDL.Record({
  'customerName' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : IDL.Text,
  'upiTransactionId' : IDL.Opt(IDL.Text),
  'shippingAddress' : ShippingAddress,
  'customerId' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'customerEmail' : IDL.Text,
});
export const OrderId = IDL.Text;
export const OrderStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Delivered' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : IDL.Text,
  'createdAt' : Timestamp,
  'upiTransactionId' : IDL.Opt(IDL.Text),
  'totalAmount' : IDL.Nat,
  'shippingAddress' : ShippingAddress,
  'customerId' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'customerEmail' : IDL.Text,
});
export const UpdateProductRequest = IDL.Record({
  'id' : ProductId,
  'stockQty' : IDL.Nat,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([AddProductRequest], [Product], []),
  'createOrder' : IDL.Func([CreateOrderRequest], [Order], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getFeaturedProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getOrdersByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Opt(Order)], []),
  'updateProduct' : IDL.Func([UpdateProductRequest], [IDL.Opt(Product)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AddProductRequest = IDL.Record({
    'stockQty' : IDL.Nat,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const ProductId = IDL.Text;
  const Timestamp = IDL.Int;
  const Product = IDL.Record({
    'id' : ProductId,
    'stockQty' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'updatedAt' : Timestamp,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const PaymentMethod = IDL.Variant({ 'COD' : IDL.Null, 'UPI' : IDL.Null });
  const ShippingAddress = IDL.Record({
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Opt(IDL.Text),
  });
  const OrderItem = IDL.Record({
    'qty' : IDL.Nat,
    'productId' : ProductId,
    'productName' : IDL.Text,
    'priceAtOrder' : IDL.Nat,
  });
  const CreateOrderRequest = IDL.Record({
    'customerName' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'customerPhone' : IDL.Text,
    'upiTransactionId' : IDL.Opt(IDL.Text),
    'shippingAddress' : ShippingAddress,
    'customerId' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'customerEmail' : IDL.Text,
  });
  const OrderId = IDL.Text;
  const OrderStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Delivered' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'customerPhone' : IDL.Text,
    'createdAt' : Timestamp,
    'upiTransactionId' : IDL.Opt(IDL.Text),
    'totalAmount' : IDL.Nat,
    'shippingAddress' : ShippingAddress,
    'customerId' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'customerEmail' : IDL.Text,
  });
  const UpdateProductRequest = IDL.Record({
    'id' : ProductId,
    'stockQty' : IDL.Nat,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([AddProductRequest], [Product], []),
    'createOrder' : IDL.Func([CreateOrderRequest], [Order], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getFeaturedProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getOrdersByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus],
        [IDL.Opt(Order)],
        [],
      ),
    'updateProduct' : IDL.Func([UpdateProductRequest], [IDL.Opt(Product)], []),
  });
};

export const init = ({ IDL }) => { return []; };