/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type OrderId = string;
export type Timestamp = bigint;
export interface AddProductRequest {
    stockQty: bigint;
    name: string;
    tags: Array<string>;
    description: string;
    discountPercent: bigint;
    imageUrl: string;
    category: string;
    rating: number;
    price: bigint;
    reviewCount: bigint;
}
export interface ShippingAddress {
    city: string;
    postalCode: string;
    state: string;
    addressLine1: string;
    addressLine2?: string;
}
export interface OrderItem {
    qty: bigint;
    productId: ProductId;
    productName: string;
    priceAtOrder: bigint;
}
export type ProductId = string;
export interface CreateOrderRequest {
    customerName: string;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    upiTransactionId?: string;
    shippingAddress: ShippingAddress;
    customerId: string;
    items: Array<OrderItem>;
    customerEmail: string;
}
export interface Order {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    createdAt: Timestamp;
    upiTransactionId?: string;
    totalAmount: bigint;
    shippingAddress: ShippingAddress;
    customerId: string;
    items: Array<OrderItem>;
    customerEmail: string;
}
export interface Product {
    id: ProductId;
    stockQty: bigint;
    name: string;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    discountPercent: bigint;
    updatedAt: Timestamp;
    imageUrl: string;
    category: string;
    rating: number;
    price: bigint;
    reviewCount: bigint;
}
export interface UpdateProductRequest {
    id: ProductId;
    stockQty: bigint;
    name: string;
    tags: Array<string>;
    description: string;
    discountPercent: bigint;
    imageUrl: string;
    category: string;
    rating: number;
    price: bigint;
    reviewCount: bigint;
}
export enum OrderStatus {
    Paid = "Paid",
    Delivered = "Delivered",
    Shipped = "Shipped",
    Pending = "Pending"
}
export enum PaymentMethod {
    COD = "COD",
    UPI = "UPI"
}
export interface backendInterface {
    addProduct(req: AddProductRequest): Promise<Product>;
    createOrder(req: CreateOrderRequest): Promise<Order>;
    deleteProduct(id: ProductId): Promise<boolean>;
    getFeaturedProducts(tag: string): Promise<Array<Product>>;
    getOrder(id: OrderId): Promise<Order | null>;
    getOrdersByCustomer(customerId: string): Promise<Array<Order>>;
    getProduct(id: ProductId): Promise<Product | null>;
    listOrders(): Promise<Array<Order>>;
    listProducts(): Promise<Array<Product>>;
    searchProducts(searchTerm: string): Promise<Array<Product>>;
    updateOrderStatus(id: OrderId, status: OrderStatus): Promise<Order | null>;
    updateProduct(req: UpdateProductRequest): Promise<Product | null>;
}
import type { CreateOrderRequest as _CreateOrderRequest, Order as _Order, OrderId as _OrderId, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, Product as _Product, ShippingAddress as _ShippingAddress, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProduct(arg0: AddProductRequest): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0);
            return result;
        }
    }
    async createOrder(arg0: CreateOrderRequest): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_CreateOrderRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_CreateOrderRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getFeaturedProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProducts(arg0);
            return result;
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByCustomer(arg0: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByCustomer(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByCustomer(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrders();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrders();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return result;
        }
    }
    async searchProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: UpdateProductRequest): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_OrderStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ShippingAddress_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShippingAddress): ShippingAddress {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: string;
    postalCode: string;
    state: string;
    addressLine1: string;
    addressLine2: [] | [string];
}): {
    city: string;
    postalCode: string;
    state: string;
    addressLine1: string;
    addressLine2?: string;
} {
    return {
        city: value.city,
        postalCode: value.postalCode,
        state: value.state,
        addressLine1: value.addressLine1,
        addressLine2: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.addressLine2))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    customerName: string;
    status: _OrderStatus;
    paymentMethod: _PaymentMethod;
    customerPhone: string;
    createdAt: _Timestamp;
    upiTransactionId: [] | [string];
    totalAmount: bigint;
    shippingAddress: _ShippingAddress;
    customerId: string;
    items: Array<_OrderItem>;
    customerEmail: string;
}): {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    createdAt: Timestamp;
    upiTransactionId?: string;
    totalAmount: bigint;
    shippingAddress: ShippingAddress;
    customerId: string;
    items: Array<OrderItem>;
    customerEmail: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n9(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_PaymentMethod_n11(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhone: value.customerPhone,
        createdAt: value.createdAt,
        upiTransactionId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.upiTransactionId)),
        totalAmount: value.totalAmount,
        shippingAddress: from_candid_ShippingAddress_n14(_uploadFile, _downloadFile, value.shippingAddress),
        customerId: value.customerId,
        items: value.items,
        customerEmail: value.customerEmail
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Paid: null;
} | {
    Delivered: null;
} | {
    Shipped: null;
} | {
    Pending: null;
}): OrderStatus {
    return "Paid" in value ? OrderStatus.Paid : "Delivered" in value ? OrderStatus.Delivered : "Shipped" in value ? OrderStatus.Shipped : "Pending" in value ? OrderStatus.Pending : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    COD: null;
} | {
    UPI: null;
}): PaymentMethod {
    return "COD" in value ? PaymentMethod.COD : "UPI" in value ? PaymentMethod.UPI : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n7(_uploadFile, _downloadFile, x));
}
function to_candid_CreateOrderRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateOrderRequest): _CreateOrderRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ShippingAddress_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShippingAddress): _ShippingAddress {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    upiTransactionId?: string;
    shippingAddress: ShippingAddress;
    customerId: string;
    items: Array<OrderItem>;
    customerEmail: string;
}): {
    customerName: string;
    paymentMethod: _PaymentMethod;
    customerPhone: string;
    upiTransactionId: [] | [string];
    shippingAddress: _ShippingAddress;
    customerId: string;
    items: Array<_OrderItem>;
    customerEmail: string;
} {
    return {
        customerName: value.customerName,
        paymentMethod: to_candid_PaymentMethod_n3(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhone: value.customerPhone,
        upiTransactionId: value.upiTransactionId ? candid_some(value.upiTransactionId) : candid_none(),
        shippingAddress: to_candid_ShippingAddress_n5(_uploadFile, _downloadFile, value.shippingAddress),
        customerId: value.customerId,
        items: value.items,
        customerEmail: value.customerEmail
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: string;
    postalCode: string;
    state: string;
    addressLine1: string;
    addressLine2?: string;
}): {
    city: string;
    postalCode: string;
    state: string;
    addressLine1: string;
    addressLine2: [] | [string];
} {
    return {
        city: value.city,
        postalCode: value.postalCode,
        state: value.state,
        addressLine1: value.addressLine1,
        addressLine2: value.addressLine2 ? candid_some(value.addressLine2) : candid_none()
    };
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    Paid: null;
} | {
    Delivered: null;
} | {
    Shipped: null;
} | {
    Pending: null;
} {
    return value == OrderStatus.Paid ? {
        Paid: null
    } : value == OrderStatus.Delivered ? {
        Delivered: null
    } : value == OrderStatus.Shipped ? {
        Shipped: null
    } : value == OrderStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    COD: null;
} | {
    UPI: null;
} {
    return value == PaymentMethod.COD ? {
        COD: null
    } : value == PaymentMethod.UPI ? {
        UPI: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
